"use client";

import { useState, useEffect } from "react";
import {
  FileText,
  CheckCircle,
  XCircle,
  Clock,
  Eye,
  ExternalLink,
  AlertCircle,
  Filter,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";

interface Article {
  _id: string;
  slug: string;
  title: string;
  excerpt: string;
  content: string;
  status: "draft" | "published" | "archived";
  contentMeta: {
    wordCount: number;
    readingTime: number;
    internalLinks: string[];
  };
  agentWorkflow?: {
    generatedBy: "agent" | "manual";
    agentIterations: number;
    agentFinalScore: number;
    agentEditHistory: any[];
    factsToVerify: any[];
    generatedAt: Date;
  };
  destinationType?: string;
  region?: string;
  createdAt: Date;
}

export default function AdminContentPage() {
  const [articles, setArticles] = useState<Article[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedArticle, setSelectedArticle] = useState<Article | null>(null);
  const [viewDialogOpen, setViewDialogOpen] = useState(false);
  const [actionLoading, setActionLoading] = useState(false);
  const [generateDialogOpen, setGenerateDialogOpen] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [generateForm, setGenerateForm] = useState({
    topic: "",
    destinationType: "",
    region: "",
  });

  // Fetch draft articles generated by agent
  useEffect(() => {
    fetchArticles();
  }, []);

  const fetchArticles = async () => {
    try {
      setLoading(true);
      const response = await fetch("/api/content/list?generatedBy=agent");
      const data = await response.json();

      if (data.success) {
        setArticles(data.articles);
      } else {
        console.error("Error fetching articles:", data.error);
      }
    } catch (error) {
      console.error("Error fetching articles:", error);
    } finally {
      setLoading(false);
    }
  };

  const handleAction = async (
    articleId: string,
    action: "approve" | "reject" | "publish"
  ) => {
    try {
      setActionLoading(true);
      const response = await fetch("/api/content/approve", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          pageId: articleId,
          action,
        }),
      });

      const data = await response.json();

      if (data.success) {
        // Refresh the article list
        await fetchArticles();
        setViewDialogOpen(false);
        alert(data.message);
      } else {
        alert("Error: " + data.error);
      }
    } catch (error) {
      console.error("Error handling action:", error);
      alert("Failed to perform action");
    } finally {
      setActionLoading(false);
    }
  };

  const handleViewArticle = (article: Article) => {
    setSelectedArticle(article);
    setViewDialogOpen(true);
  };

  const handleGenerateArticle = async () => {
    if (!generateForm.topic.trim()) {
      alert("Please enter a topic");
      return;
    }

    try {
      setGenerating(true);
      const response = await fetch("/api/content/generate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(generateForm),
      });

      const data = await response.json();

      if (data.success) {
        // Check if article was approved or rejected after multiple attempts
        if (data.status === "approved") {
          // Article was approved by editor
          alert(`✅ ${data.message}`);
        } else if (data.editHistory && data.editHistory.length > 0) {
          // Article was rejected - show detailed feedback
          const lastReview = data.editHistory[data.editHistory.length - 1];

          if (lastReview.editorDecision === "reject") {
            const errorDetails = `
⚠️ Article Rejected After ${data.editHistory.length} Attempt(s)

Topic: "${generateForm.topic}"
Final Score: ${lastReview.editorScore}/100

SUMMARY:
${lastReview.editorSummary}

ISSUES FOUND (${lastReview.issues.length} total):
${lastReview.issues.slice(0, 5).map((issue: any, i: number) =>
  `${i + 1}. [${issue.severity.toUpperCase()}] ${issue.category}
   → ${issue.description}
   → Location: ${issue.location}
   → Fix: ${issue.suggestion}`
).join('\n\n')}${lastReview.issues.length > 5 ? `\n\n... and ${lastReview.issues.length - 5} more issue(s)` : ''}

REQUIRED CHANGES:
${lastReview.requiredChanges.map((change: string, i: number) => `${i + 1}. ${change}`).join('\n')}

---
The article has been saved as DRAFT for manual review and editing.
You can find it in the content list below.
            `.trim();

            alert(errorDetails);
          } else {
            alert(`✅ ${data.message}`);
          }
        } else {
          alert(`✅ ${data.message}`);
        }

        setGenerateDialogOpen(false);
        setGenerateForm({ topic: "", destinationType: "", region: "" });
        await fetchArticles();
      } else {
        // API error (not just rejections)
        let errorMsg = `❌ Error: ${data.error || "Unknown error"}`;

        if (data.message) {
          errorMsg += `\n\nDetails: ${data.message}`;
        }

        // If there's edit history, show last rejection details
        if (data.editHistory && data.editHistory.length > 0) {
          const lastReview = data.editHistory[data.editHistory.length - 1];
          errorMsg += `\n\nLast Review (Iteration ${data.iterations}):\n`;
          errorMsg += `Score: ${lastReview.editorScore}/100\n`;
          errorMsg += `Summary: ${lastReview.editorSummary}\n`;
          errorMsg += `\nIssues: ${lastReview.issues.length} (${lastReview.issues.filter((i: any) => i.severity === "critical").length} critical)`;
        }

        alert(errorMsg);
      }
    } catch (error) {
      console.error("Error generating article:", error);
      alert("❌ Failed to generate article. Please check the console for details.");
    } finally {
      setGenerating(false);
    }
  };

  const agentGeneratedArticles = articles.filter(
    (a) => a.agentWorkflow?.generatedBy === "agent"
  );
  const pendingCount = agentGeneratedArticles.filter((a) => a.status === "draft").length;
  const publishedCount = agentGeneratedArticles.filter(
    (a) => a.status === "published"
  ).length;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-2xl md:text-3xl font-bold text-gray-900">
          Content Review
        </h1>
        <p className="text-gray-600 mt-1">
          Review and approve AI-generated travel articles.
        </p>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <Card>
          <CardContent className="pt-6">
            <div className="text-2xl font-bold text-yellow-600">{pendingCount}</div>
            <p className="text-sm text-gray-600">Pending Review</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="text-2xl font-bold text-emerald-600">
              {publishedCount}
            </div>
            <p className="text-sm text-gray-600">Published</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="text-2xl font-bold text-blue-600">
              {agentGeneratedArticles.length}
            </div>
            <p className="text-sm text-gray-600">Total Generated</p>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="pt-6">
            <div className="text-2xl font-bold text-purple-600">
              {agentGeneratedArticles.reduce(
                (sum, a) => sum + (a.agentWorkflow?.agentIterations || 0),
                0
              ) / (agentGeneratedArticles.length || 1)}
            </div>
            <p className="text-sm text-gray-600">Avg Iterations</p>
          </CardContent>
        </Card>
      </div>

      {/* Generate New Content Button */}
      <div className="flex justify-end">
        <Button
          className="bg-blue-600 hover:bg-blue-700"
          onClick={() => setGenerateDialogOpen(true)}
        >
          <FileText className="h-4 w-4 mr-2" />
          Generate New Article
        </Button>
      </div>

      {/* Article List */}
      <div className="space-y-4">
        {loading ? (
          <div className="text-center py-12">
            <p className="text-gray-600">Loading articles...</p>
          </div>
        ) : agentGeneratedArticles.length === 0 ? (
          <Card>
            <CardContent className="pt-6">
              <div className="text-center py-12">
                <FileText className="h-12 w-12 text-gray-400 mx-auto mb-4" />
                <h3 className="text-lg font-semibold text-gray-900 mb-2">
                  No articles yet
                </h3>
                <p className="text-gray-600 mb-6">
                  Generate your first AI-powered travel article to get started.
                </p>
                <Button
                  className="bg-blue-600 hover:bg-blue-700"
                  onClick={() => setGenerateDialogOpen(true)}
                >
                  <FileText className="h-4 w-4 mr-2" />
                  Generate Article
                </Button>
              </div>
            </CardContent>
          </Card>
        ) : (
          agentGeneratedArticles.map((article) => (
            <Card key={article._id}>
              <CardContent className="pt-6">
                <div className="flex items-start gap-4">
                  <div
                    className={`p-2 rounded-full ${
                      article.status === "draft"
                        ? "bg-yellow-100 text-yellow-600"
                        : article.status === "published"
                        ? "bg-emerald-100 text-emerald-600"
                        : "bg-gray-100 text-gray-600"
                    }`}
                  >
                    {article.status === "draft" ? (
                      <Clock className="h-5 w-5" />
                    ) : article.status === "published" ? (
                      <CheckCircle className="h-5 w-5" />
                    ) : (
                      <XCircle className="h-5 w-5" />
                    )}
                  </div>

                  <div className="flex-1">
                    <div className="flex items-start justify-between gap-4">
                      <div>
                        <h3 className="font-semibold text-gray-900">
                          {article.title}
                        </h3>
                        <p className="text-sm text-gray-600 mt-1">
                          {article.excerpt}
                        </p>
                      </div>
                      <div className="flex items-center gap-2">
                        <Badge
                          className={
                            article.status === "draft"
                              ? "bg-yellow-50 text-yellow-600"
                              : article.status === "published"
                              ? "bg-emerald-50 text-emerald-600"
                              : "bg-gray-50 text-gray-600"
                          }
                        >
                          {article.status}
                        </Badge>
                        {article.destinationType && (
                          <Badge variant="outline" className="capitalize">
                            {article.destinationType}
                          </Badge>
                        )}
                        {article.region && (
                          <Badge variant="outline" className="capitalize">
                            {article.region}
                          </Badge>
                        )}
                      </div>
                    </div>

                    {article.agentWorkflow && (
                      <div className="mt-4 p-4 bg-gray-50 rounded-lg">
                        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
                          <div>
                            <span className="text-gray-600">Word Count</span>
                            <div className="font-semibold text-gray-900">
                              {article.contentMeta.wordCount.toLocaleString()}
                            </div>
                          </div>
                          <div>
                            <span className="text-gray-600">Reading Time</span>
                            <div className="font-semibold text-gray-900">
                              {article.contentMeta.readingTime} min
                            </div>
                          </div>
                          <div>
                            <span className="text-gray-600">Agent Score</span>
                            <div className="font-semibold text-gray-900">
                              {article.agentWorkflow.agentFinalScore}/100
                            </div>
                          </div>
                          <div>
                            <span className="text-gray-600">Iterations</span>
                            <div className="font-semibold text-gray-900">
                              {article.agentWorkflow.agentIterations}
                            </div>
                          </div>
                        </div>

                        {article.agentWorkflow.factsToVerify.length > 0 && (
                          <div className="mt-3 flex items-center gap-2 text-sm text-amber-600">
                            <AlertCircle className="h-4 w-4" />
                            <span>
                              {article.agentWorkflow.factsToVerify.length} facts need
                              verification
                            </span>
                          </div>
                        )}
                      </div>
                    )}

                    <div className="flex gap-3 mt-4">
                      <Button
                        variant="outline"
                        onClick={() => handleViewArticle(article)}
                      >
                        <Eye className="h-4 w-4 mr-2" />
                        Review
                      </Button>

                      {article.status === "draft" && (
                        <>
                          <Button
                            className="bg-emerald-600 hover:bg-emerald-700"
                            onClick={() => handleAction(article._id, "publish")}
                            disabled={actionLoading}
                          >
                            <CheckCircle className="h-4 w-4 mr-2" />
                            Publish
                          </Button>
                          <Button
                            variant="outline"
                            onClick={() => handleAction(article._id, "reject")}
                            disabled={actionLoading}
                          >
                            <XCircle className="h-4 w-4 mr-2" />
                            Reject
                          </Button>
                        </>
                      )}

                      {article.status === "published" && (
                        <Button variant="outline" asChild>
                          <a
                            href={`/vietnam/destinations/${article.slug}`}
                            target="_blank"
                            rel="noopener noreferrer"
                          >
                            <ExternalLink className="h-4 w-4 mr-2" />
                            View Live
                          </a>
                        </Button>
                      )}
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))
        )}
      </div>

      {/* View Article Dialog */}
      <Dialog open={viewDialogOpen} onOpenChange={setViewDialogOpen}>
        <DialogContent className="max-w-4xl max-h-[80vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>{selectedArticle?.title}</DialogTitle>
            <DialogDescription>
              Review the article content and agent feedback
            </DialogDescription>
          </DialogHeader>

          {selectedArticle && (
            <div className="space-y-6">
              {/* Metadata */}
              <div className="grid grid-cols-2 gap-4 p-4 bg-gray-50 rounded-lg">
                <div>
                  <span className="text-sm text-gray-600">Word Count</span>
                  <div className="font-semibold">
                    {selectedArticle.contentMeta.wordCount.toLocaleString()}
                  </div>
                </div>
                <div>
                  <span className="text-sm text-gray-600">Internal Links</span>
                  <div className="font-semibold">
                    {selectedArticle.contentMeta.internalLinks.length}
                  </div>
                </div>
                {selectedArticle.agentWorkflow && (
                  <>
                    <div>
                      <span className="text-sm text-gray-600">Agent Score</span>
                      <div className="font-semibold">
                        {selectedArticle.agentWorkflow.agentFinalScore}/100
                      </div>
                    </div>
                    <div>
                      <span className="text-sm text-gray-600">Iterations</span>
                      <div className="font-semibold">
                        {selectedArticle.agentWorkflow.agentIterations}
                      </div>
                    </div>
                  </>
                )}
              </div>

              {/* Excerpt */}
              <div>
                <h4 className="font-semibold text-gray-900 mb-2">Excerpt</h4>
                <p className="text-sm text-gray-700">{selectedArticle.excerpt}</p>
              </div>

              {/* Content Preview */}
              <div>
                <h4 className="font-semibold text-gray-900 mb-2">
                  Content Preview
                </h4>
                <div className="prose prose-sm max-w-none p-4 bg-gray-50 rounded-lg max-h-96 overflow-y-auto">
                  <pre className="whitespace-pre-wrap text-sm text-gray-700">
                    {selectedArticle.content.substring(0, 2000)}...
                  </pre>
                </div>
              </div>

              {/* Facts to Verify */}
              {selectedArticle.agentWorkflow &&
                selectedArticle.agentWorkflow.factsToVerify.length > 0 && (
                  <div>
                    <h4 className="font-semibold text-gray-900 mb-2">
                      Facts to Verify
                    </h4>
                    <div className="space-y-2">
                      {selectedArticle.agentWorkflow.factsToVerify.map(
                        (fact: any, index: number) => (
                          <div
                            key={index}
                            className="p-3 bg-amber-50 border border-amber-200 rounded-lg"
                          >
                            <div className="flex items-start gap-2">
                              <AlertCircle className="h-4 w-4 text-amber-600 mt-0.5" />
                              <div className="flex-1">
                                <p className="text-sm text-gray-900">{fact.claim}</p>
                                <p className="text-xs text-gray-600 mt-1">
                                  Location: {fact.location} • Priority: {fact.priority}
                                </p>
                              </div>
                            </div>
                          </div>
                        )
                      )}
                    </div>
                  </div>
                )}

              {/* Actions */}
              {selectedArticle.status === "draft" && (
                <div className="flex gap-3 pt-4 border-t">
                  <Button
                    className="bg-emerald-600 hover:bg-emerald-700"
                    onClick={() => handleAction(selectedArticle._id, "publish")}
                    disabled={actionLoading}
                  >
                    <CheckCircle className="h-4 w-4 mr-2" />
                    Publish Article
                  </Button>
                  <Button
                    variant="outline"
                    onClick={() => handleAction(selectedArticle._id, "reject")}
                    disabled={actionLoading}
                  >
                    <XCircle className="h-4 w-4 mr-2" />
                    Reject Article
                  </Button>
                </div>
              )}
            </div>
          )}
        </DialogContent>
      </Dialog>

      {/* Generate Article Dialog */}
      <Dialog open={generateDialogOpen} onOpenChange={setGenerateDialogOpen}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>Generate New Article</DialogTitle>
            <DialogDescription>
              Enter the topic and filters for the AI to generate a travel article
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-900 mb-2">
                Topic <span className="text-red-500">*</span>
              </label>
              <input
                type="text"
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="e.g., Complete guide to visiting Hanoi"
                value={generateForm.topic}
                onChange={(e) =>
                  setGenerateForm({ ...generateForm, topic: e.target.value })
                }
                disabled={generating}
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-900 mb-2">
                Destination Type (Optional)
              </label>
              <select
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                value={generateForm.destinationType}
                onChange={(e) =>
                  setGenerateForm({
                    ...generateForm,
                    destinationType: e.target.value,
                  })
                }
                disabled={generating}
              >
                <option value="">Select type...</option>
                <option value="city">City</option>
                <option value="region">Region</option>
                <option value="beach">Beach</option>
                <option value="mountain">Mountain</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-900 mb-2">
                Region (Optional)
              </label>
              <select
                className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
                value={generateForm.region}
                onChange={(e) =>
                  setGenerateForm({ ...generateForm, region: e.target.value })
                }
                disabled={generating}
              >
                <option value="">Select region...</option>
                <option value="north">North Vietnam</option>
                <option value="central">Central Vietnam</option>
                <option value="south">South Vietnam</option>
              </select>
            </div>

            <div className="flex gap-3 pt-4">
              <Button
                className="flex-1 bg-blue-600 hover:bg-blue-700"
                onClick={handleGenerateArticle}
                disabled={generating}
              >
                {generating ? (
                  <>
                    <Clock className="h-4 w-4 mr-2 animate-spin" />
                    Generating... (2-5 min)
                  </>
                ) : (
                  <>
                    <FileText className="h-4 w-4 mr-2" />
                    Generate Article
                  </>
                )}
              </Button>
              <Button
                variant="outline"
                onClick={() => setGenerateDialogOpen(false)}
                disabled={generating}
              >
                Cancel
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
